/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ArtistService } from './services/artist.service';
export { FilmService } from './services/film.service';
