/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Film } from '../models/film';
export interface Artist {
  birthdate?: string;
  filmIds?: Array<string> | null;
  films?: Array<Film> | null;
  id?: string | null;
  listeners?: number;
  name?: string;
}
