/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Film {
  id?: string | null;
  isStreamable?: boolean;
  name?: string;
  releaseDate?: string;
  time?: number;
}
