/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Artist } from '../../models/artist';

export interface ApiArtistIdGet$Plain$Params {
  id: string;
}

export function apiArtistIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiArtistIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Artist>> {
  const rb = new RequestBuilder(rootUrl, apiArtistIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Artist>;
    })
  );
}

apiArtistIdGet$Plain.PATH = '/api/Artist/{id}';
