/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Artist } from '../../models/artist';

export interface ApiArtistPost$Json$Params {
      body: Artist
}

export function apiArtistPost$Json(http: HttpClient, rootUrl: string, params: ApiArtistPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Artist>> {
  const rb = new RequestBuilder(rootUrl, apiArtistPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Artist>;
    })
  );
}

apiArtistPost$Json.PATH = '/api/Artist';
