/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiArtistArtistIdDeleteFilmFilmIdDelete$Params {
  artistId: string;
  filmId: string;
}

export function apiArtistArtistIdDeleteFilmFilmIdDelete(http: HttpClient, rootUrl: string, params: ApiArtistArtistIdDeleteFilmFilmIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiArtistArtistIdDeleteFilmFilmIdDelete.PATH, 'delete');
  if (params) {
    rb.path('artistId', params.artistId, {});
    rb.path('filmId', params.filmId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiArtistArtistIdDeleteFilmFilmIdDelete.PATH = '/api/Artist/{artistId}/deleteFilm/{filmId}';
