/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiArtistArtistIdAddFilmFilmIdPost$Params {
  artistId: string;
  filmId: string;
}

export function apiArtistArtistIdAddFilmFilmIdPost(http: HttpClient, rootUrl: string, params: ApiArtistArtistIdAddFilmFilmIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiArtistArtistIdAddFilmFilmIdPost.PATH, 'post');
  if (params) {
    rb.path('artistId', params.artistId, {});
    rb.path('filmId', params.filmId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiArtistArtistIdAddFilmFilmIdPost.PATH = '/api/Artist/{artistId}/addFilm/{filmId}';
